version: 2
jobs:
  test:
    working_directory: /tmp/workspace
    parallelism: 1
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y make cmake g++ python
      - run: make all
      - store_artifacts:
          path: out/test_result.xml

workflows:
  version: 2
  test:
    jobs:
      - test
