#define EXT_SINGULAR          1
#define EXT_DEPTH_CHECK       2
#define EXT_DEPTH_ONE_REPLY   3
#define EXT_DEPTH_RECAP       2
#define NULL_DEPTH_RATE       13
#define NULL_DEPTH_REDUCE     14
#define NULL_DEPTH_VRATE      510
#define REDUCTION_RATE1       9
#define REDUCTION_RATE2       12
#define RAZOR_MARGIN1         230
#define RAZOR_MARGIN2         675
#define RAZOR_MARGIN3         820
#define RAZOR_MARGIN4         630
#define FUT_PRUN_MAX_DEPTH    20
#define FUT_PRUN_MARGIN_RATE  70
#define FUT_PRUN_MARGIN       73
#define PROBCUT_MARGIN        219
#define PROBCUT_REDUCTION     5
#define ASP_MIN_DEPTH         5
#define ASP_1ST_DELTA         82
#define ASP_DELTA_RATE        17
#define SINGULAR_DEPTH        6
#define SINGULAR_MARGIN       21