#define EXT_SINGULAR          2
#define EXT_DEPTH_CHECK       2
#define EXT_DEPTH_ONE_REPLY   2
#define EXT_DEPTH_RECAP       3
#define NULL_DEPTH_RATE       12
#define NULL_DEPTH_REDUCE     12
#define NULL_DEPTH_VRATE      500
#define REDUCTION_RATE1       10
#define REDUCTION_RATE2       10
#define RAZOR_MARGIN1         250
#define RAZOR_MARGIN2         650
#define RAZOR_MARGIN3         800
#define RAZOR_MARGIN4         650
#define FUT_PRUN_MAX_DEPTH    20
#define FUT_PRUN_MARGIN_RATE  60
#define FUT_PRUN_MARGIN       75
#define PROBCUT_MARGIN        225
#define PROBCUT_REDUCTION     4
#define ASP_MIN_DEPTH         6
#define ASP_1ST_DELTA         64
#define ASP_DELTA_RATE        25
#define SINGULAR_DEPTH        6
#define SINGULAR_MARGIN       20