#define EXT_SINGULAR          2
#define EXT_DEPTH_CHECK       1
#define EXT_DEPTH_ONE_REPLY   3
#define EXT_DEPTH_RECAP       2
#define NULL_DEPTH_RATE       12
#define NULL_DEPTH_REDUCE     14
#define NULL_DEPTH_VRATE      475
#define REDUCTION_RATE1       8
#define REDUCTION_RATE2       12
#define RAZOR_MARGIN1         225
#define RAZOR_MARGIN2         675
#define RAZOR_MARGIN3         800
#define RAZOR_MARGIN4         670
#define FUT_PRUN_MAX_DEPTH    20
#define FUT_PRUN_MARGIN_RATE  62
#define FUT_PRUN_MARGIN       85
#define PROBCUT_MARGIN        219
#define PROBCUT_REDUCTION     16
#define ASP_MIN_DEPTH         7
#define ASP_1ST_DELTA         82
#define ASP_DELTA_RATE        23
#define SINGULAR_DEPTH        32
#define SINGULAR_MARGIN       3
